##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user >", color = "(RD)"}
hostname  = {icon = " ", name = "hostname >", color = "(YW)"}
uptime    = {icon = " ", name = "uptime >", color = "(BE)"}
sep_color = "SEPARATOR"
# uptime    = {icon = " ", name = "uptime >", color = "(BE)"}
distro    = {icon = " ", name = "distro >", color = "(GN)"}
kernel    = {icon = " ", name = "kernel >", color = "(MA)"}
cpu       = {icon = " ", name = "cpu >", color = "(RD)"}
memory    = {icon = " ", name = "memory >", color = "(YW)"}
desktop   = {icon = " ", name = "desktop >", color = "(CN)"}
terminal  = {icon = " ", name = "term >", color = "(RD)"}
shell     = {icon = " ", name = "shell >", color = "(MA)"}
 packages  = {icon = " ", name = "pkgs >", color = "(RD)"}
sep_line1 = "SEPARATOR"
 weather   = {icon = " ", name = "weather >", color = "(BE)"}
# gpu       = {icon = "󱔐 ", name = "gpu >", color = "(MA)"}
# cpu       = {icon = " ", name = "cpu >", color = "(RD)"}
# battery   = {icon = " ", name = "battery", color = "(GN)"}
# memory    = {icon = " ", name = "memory >", color = "(YW)"}
# The following stats do not work on MacOS and the BSDs.
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
sep_line = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "doubleline"
layout  = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 1
location = "Chicago"





